name: Keep Supabase DB Alive

on:
  schedule:
    - cron: '0 6 * * *' # runs daily at 6 AM UTC
  workflow_dispatch: # allows manual trigger

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Ping Supabase API
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          curl -sS "${SUPABASE_URL}/rest/v1/saved_trips?select=id&limit=1" \
            -H "apikey: ${SUPABASE_ANON_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_ANON_KEY}" \
            --fail
